
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njjxqxluxtyechxgtwsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qanhxeGx1eHR5ZWNoeGd0d3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDA2NTQsImV4cCI6MjA1OTQxNjY1NH0.BgfdFH9LspMaEpYADgnl2vBFQu05Up0A8ggH9XsUHSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
